{
    'name': "My Bike Shop",
    'summary': "Module de gestion pour un magasin de vélos",
    'description': "Gestion de vélos et locations",
    'author': "Yazbeck John et Jose Bigoro",
    'website': "https://github.com/sambiig/ERP-Project",
    'category': 'Sales',
    'version': '0.1',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'stock',
        'account',
        'contacts',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/bike_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}